remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
title: "The Pitfalls of Porting Code to the GPU"
description: "Common mistakes beginners might make when porting code to the GPU"
author:
  name: Tudor Szabo
